### ISSUE TITLE
Syntax error when installing module

### ISSUE THREAD

**Issue by alexsegura** [nenes25/prestashop_console#195]
#### Describe the bug

I am running `prestashop_console` on [CircleCI](https://github.com/coopcycle/coopcycle-plugins/blob/afa7e690f932826e589b70e9f3fe91d895733912/.circleci/config.yml), and tests have started failing with the following error:

```
#!/bin/bash -eo pipefail
mv ./prestashop /var/www/html/modules/coopcycle
cd /var/www/html
./prestashopConsole.phar module:install coopcycle
PHP Parse error:  syntax error, unexpected ':', expecting '{' in phar:///var/www/html/prestashopConsole.phar/src/vendor/symfony/polyfill-php80/bootstrap.php on line 23

Exited with code exit status 255
CircleCI received exit code 255
```

### PrestashopConsole Version

`latest`

### Prestashop Version

`1.6`

### Php Version

~I am not sure about the version, because it is inherited from the PrestaShop image.~

I printed the version, and it's using PHP 5.6.40 🤦

**Comment by nenes25** [comment]
Hello Alexandre,

Thanks for the report 
I've also have this issue which is related to composer-dev librairies which require wrong files.
The fix is already in dev branch, could you try to download this file and tell me if everything works fine ?
It should be fixed in next release 
https://github.com/nenes25/prestashop_console/blob/dev/bin/prestashopConsole.phar
Regards,

**Comment by alexsegura** [comment]
@nenes25 thanks a lot, the dev branch works 🙂 

https://github.com/coopcycle/coopcycle-plugins/commit/592a06d89a9c486e2ffdb75b200b11f649338e98

**Comment by nenes25** [comment]
Great,
I'll get back you through this issue once the new release fix this.
Because you may encounter later some errors, when working with the dev branch as its not fully stable.
